### ISSUE TITLE
DateFormatter is not thread safe

### ISSUE THREAD

**Issue by 0xTim** [apple/swift-corelibs-foundation#3166]
The `DateFormatter` is not thread safe - https://github.com/apple/swift-corelibs-foundation/blob/bfead15ba7a547a8e2ea79dfd8be97de1153245d/Sources/Foundation/DateFormatter.swift#L190-L201

This is inconsistent with the behaviour and description of the Objective-C Foundation implementation - https://developer.apple.com/documentation/foundation/dateformatter

**Comment by 0xTim** [comment]
Raised earlier under apple/swift#50285

**Comment by dimitribouniol** [comment]
This seems fixed in main: https://swiftfiddle.com/qmuoxrfh3jehjgvqee5tevdwhm?c=H4sIAAAAAAAAA1WR3WoCMRCFX2WaG7PQDVH6u%2BBVxVqotGUtlRJY0t2ooZuJJLEg4rs3UWvZmZsTZj7mTGZHalIQbdbWBRjbDTYyaIsiZqsCLKwzMgTlYAgjGdT4700zgeciq2WrIpm6Hk6S6kZh0AutXAFMe3t3w%2FsdqLUJi8jzQXQAQRRW72X1%2BlI%2BzQXpcEEb9WkxkbOTpF7VFhs%2FdtY8TmcF8A7RnJ1HRpBtjHw6zZumN%2BtNJoUxhfesLMt5CkHS8hGGCjQCZ4z17zmHnUCAkfZrGerV20ZtFFu29ku2NGPSb7E%2BdgBI75UL9H%2B8D07jki6iueLwizTLYJicDPjgKue3Ob8%2B7AiwF7hP49eRCFSQD%2Bu%2B%2FUUskkvyEw%2BFerkK7TY3UiPZ%2FwJfjBiwvQEAAA%3D%3D

**Comment by parkera** [comment]
Thanks for checking @dimitribouniol.
