### ISSUE TITLE
fatal error: import of shadowed module '_FoundationICU'

### ISSUE THREAD

**Issue by Coeur** [apple/swift-corelibs-foundation#5023]
I checked the readme of the project: it says just do `swift build`.
I tried it and I get:
```
➜  swift-corelibs-foundation git:(main) ✗ swift build
Building for debugging...
In file included from <built-in>:1:
/Users/User/Developer/swift-corelibs-foundation/Sources/CoreFoundation/internalInclude/CoreFoundation_Prefix.h:20:5: warning: 'TARGET_OS_WASI' is not defined, evaluates to 0 [-Wundef-prefix=TARGET_OS_]
   20 | #if TARGET_OS_WASI
      |     ^
/Users/User/Developer/swift-corelibs-foundation/.build/checkouts/swift-foundation-icu/icuSources/include/_foundation_unicode/module.modulemap:1:8: fatal error: import of shadowed module '_FoundationICU'
    1 | module _FoundationICU {
      |        ^
/Users/User/Developer/swift-corelibs-foundation/.build/arm64-apple-macosx/debug/_FoundationICU.build/module.modulemap:1:8: note: previous definition is here
    1 | module _FoundationICU {
      |        ^
/Users/User/Developer/swift-corelibs-foundation/Sources/CoreFoundation/CFStringUtilities.c:22:10: note: submodule of top-level module '_FoundationICU' implicitly imported here
   22 | #include <_foundation_unicode/ucol.h>
      |          ^
1 warning and 1 error generated.
```

I'm on:
- macOS 15.0 beta 3 (24A5289h)
- Xcode 16.0 beta 3 (16A5202i)

**Comment by parkera** [comment]
swift-corelibs-foundation won't build for macOS. [swift-foundation](http://github.com/apple/swift-foundation) will, though.

**Comment by Coeur** [comment]
That's not helpful. It's a different codebase.

**Comment by parkera** [comment]
Building swift-corelibs-foundation for macOS doesn't really help us meet its goals. Using XCTest brings in the system frameworks at the same time, so it is confusing to see which Foundation you're actually using at any time. In the time since the project was started, we have had a lot of advances in the industry of using containers to set up consistent environments for building and testing, and Swift now provides them for a large variety of platforms. We think that is the best way to work on the project because it is a lot more faithful to the environment used in production.
