### ISSUE TITLE
add AffineTransformComponents

### ISSUE THREAD

**Issue by songhuaixu** [apple/swift-corelibs-foundation#5050]

**Comment by jmschonfeld** [comment]
Are you able to clarify which API you're referring to exactly, are you referring to the `CGAffineTransformComponents` type provided by CoreGraphics on Darwin platforms, or is there a different Foundation API that you're referring to?

**Comment by songhuaixu** [comment]
> Are you able to clarify which API you're referring to exactly, are you referring to the `CGAffineTransformComponents` type provided by CoreGraphics on Darwin platforms, or is there a different Foundation API that you're referring to?

Yes, what I mean is `CGAffineTransformComponents`

**Comment by jmschonfeld** [comment]
Unfortunately I don't think we'll be adding that type to Foundation's API here. That type is a C type that is defined by the CoreGraphics framework (which is not open source or part of the swift toolchain). Do you have APIs that you want to write in non-Darwin Swift that you feel would need this type? If so, you're welcome to make an API proposal/pitch for a new Foundation API that would serve that purpose. However, since this is a C API (not Swift) and it is not owned by Foundation (it's a CoreGraphics type which is Darwin only) it wouldn't be a type that we'd add here to Foundation

**Comment by itingliu** [comment]
Closing due to lack of clarity of the ER.
